server:
  port: ${SERVER_PORT:40100}
spring:
  application:
    name: relax-search-service
relax:
  elasticsearch:
    hostList: ${ES_HOST_PORT_LIST:127.0.0.1:9200} #多个结点中间用逗号分隔
  course:
    index: relax_course
    type: doc
    source_field: id,name,grade,first_level_tag,second_level_tag,charge,valid,pic,qq,price,price_old,status,study_model,teach_mode,expires,pub_time,start_time,end_time
  media:
    index:
    type:
    source_field: